In [2]:
import pandas as pd

vessel_movements_PPT_df = pd.read_csv('C:\\Users\\SSY\\Downloads\\hackatho\\vessel_movements-20240126T094919Z-001\\vessel_movements_PPT.csv')

vessel_movements_PPT_df

,imo,mmsi,vessel_id,vessel_name,date_of_build,vessel_type,group,timestamp,date_only,lon,...,anchorage,terminal,maneuvering_zone,p,vref,sfc_me,sfc_ae,sfc_ab,ael,abl
0,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:42.000Z,2023-09-17,103.826065,...,PPT Anchorage,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0
1,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:44.000Z,2023-09-17,103.826065,...,PPT Anchorage,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0
2,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:43.000Z,2023-09-17,103.825690,...,PPT Anchorage,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0
3,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:45.000Z,2023-09-17,103.825690,...,PPT Anchorage,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0
4,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:10:42.000Z,2023-09-17,103.825580,...,PPT Anchorage,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822594,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:59:17.000Z,2023-08-21,103.761665,...,NaN,NaN,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,NaN,NaN
2822595,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:02:17.000Z,2023-08-21,103.761665,...,NaN,NaN,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,4493.0,908.0
2822596,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:58:47.000Z,2023-08-21,103.783330,...,NaN,NaN,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,NaN,NaN
2822597,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:47.000Z,2023-08-21,103.783330,...,NaN,NaN,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,2503.0,436.0
2822598,9450313,636091832,647462,Northern Priority,2009-10-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:40.000Z,2023-08-21,103.766670,...,NaN,NaN,PPT Maneouvering Zone,36560.0,22.5,172.91,195.0,300.0,NaN,NaN

In [3]:
for column in vessel_movements_PPT_df.select_dtypes(include=['float64', 'int64']).columns:
    vessel_movements_PPT_df[column].fillna(0, inplace=True)

for column in vessel_movements_PPT_df.select_dtypes(include=['object']).columns:
    vessel_movements_PPT_df[column].fillna('Unknown', inplace=True)

In [4]:
vessel_movements_PPT_df.isnull().sum()

imo                      0
mmsi                     0
vessel_id                0
vessel_name              0
date_of_build            0
vessel_type              0
group                    0
timestamp                0
date_only                0
lon                      0
lat                      0
nav_stat                 0
speed                    0
course                   0
heading                  0
fuel_category            0
main_engine_fuel_type    0
aux_engine_fuel_type     0
engine_type              0
berth                    0
port_name                0
coverage                 0
anchorage                0
terminal                 0
maneuvering_zone         0
p                        0
vref                     0
sfc_me                   0
sfc_ae                   0
sfc_ab                   0
ael                      0
abl                      0
dtype: int64

In [5]:

total_rows = vessel_movements_PPT_df.shape[0]

unique_rows = len(vessel_movements_PPT_df.drop_duplicates())
print(unique_rows)
print(total_rows)

2822599
2822599

In [8]:
#qns 3---------------------

In [14]:
print(vessel_movements_PPT_df["vessel_type"].unique())
print("----------------------------------")
print(vessel_movements_PPT_df["group"].unique())

['Crude/Oil Products Tanker' 'Products Tanker' 'Bunkering Tanker'
 'Utility Vessel' 'Chemical/Products Tanker'
 'Container Ship (Fully Cellular)' 'Tug' 'Pusher Tug' 'Crude Oil Tanker'
 'General Cargo Ship' 'Platform Supply Ship' 'Crew/Supply Vessel'
 'Anchor Handling Vessel' 'Drilling Rig, jack up' 'Fishing Vessel'
 'Landing Craft' 'Passenger Ship' 'Cement Carrier' 'Bulk Carrier'
 'Asphalt/Bitumen Tanker' 'General Cargo Ship (with Ro-Ro facility)'
 'Anchor Handling Tug Supply' 'Vehicles Carrier' 'Water Tanker'
 'Fish Carrier' 'Trailing Suction Hopper Dredger' 'Open Hatch Cargo Ship'
 'Offshore Support Vessel' 'Yacht' 'Research Survey Vessel'
 'Deck Cargo Ship' 'Aggregates Carrier' 'Refrigerated Cargo Ship'
 'Diving Support Vessel' 'Crane Vessel, non propelled'
 'Passenger/Landing Craft' 'Passenger/Ro-Ro Ship (Vehicles)'
 'Ro-Ro Cargo Ship' 'Heavy Load Carrier' 'LPG Tanker' 'Buoy Tender'
 'Chemical Tanker' 'Unknown' 'Passenger/Cruise' 'Waste Disposal Vessel'
 'Cutter Suction Dredger' 'LPG/Chemical Tanker' 'Pipe Layer Crane Vessel'
 'Offshore Tug/Supply Ship' 'Wood Chips Carrier' 'Cable Layer'
 'Work/Repair Vessel' 'Livestock Carrier' 'Hopper, Motor'
 'Heavy Load Carrier, semi submersible' 'Crane Vessel' 'Mooring Vessel']
----------------------------------
['Crude & Products Tanker' 'Offshore Support Vessel' 'Chemical Tanker'
 'Container Ship' 'Tug Boat' 'General Cargo' 'Other' 'Passenger/Cruise'
 'Bulk Carrier' 'Auto Carrier' 'Reefer' 'RoRo' 'LPG Tanker']

In [15]:

vessel_movements_PPT_df['OGV'] = vessel_movements_PPT_df['group'].apply(lambda x: 'OGV' if x in ['Crude & Products Tanker', 'Offshore Support Vessel', 'Chemical Tanker', 'Container Ship', 'General Cargo','Passenger/Cruise', 'Bulk Carrier', 'Auto Carrier', 'Reefer', 'RoRo', 'LPG Tanker'] else 'Non-OGV')
vessel_movements_PPT_df

,imo,mmsi,vessel_id,vessel_name,date_of_build,vessel_type,group,timestamp,date_only,lon,...,terminal,maneuvering_zone,p,vref,sfc_me,sfc_ae,sfc_ab,ael,abl,OGV
0,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:42.000Z,2023-09-17,103.826065,...,Unknown,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV
1,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:44.000Z,2023-09-17,103.826065,...,Unknown,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV
2,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:43.000Z,2023-09-17,103.825690,...,Unknown,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV
3,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:45.000Z,2023-09-17,103.825690,...,Unknown,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV
4,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:10:42.000Z,2023-09-17,103.825580,...,Unknown,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822594,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:59:17.000Z,2023-08-21,103.761665,...,Unknown,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,0.0,0.0,OGV
2822595,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:02:17.000Z,2023-08-21,103.761665,...,Unknown,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,4493.0,908.0,OGV
2822596,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:58:47.000Z,2023-08-21,103.783330,...,Unknown,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,0.0,0.0,OGV
2822597,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:47.000Z,2023-08-21,103.783330,...,Unknown,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,2503.0,436.0,OGV
2822598,9450313,636091832,647462,Northern Priority,2009-10-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:40.000Z,2023-08-21,103.766670,...,Unknown,PPT Maneouvering Zone,36560.0,22.5,172.91,195.0,300.0,0.0,0.0,OGV

In [16]:
#for checking

ogv_df = vessel_movements_PPT_df[vessel_movements_PPT_df['OGV'] == 'OGV']

unique_groups = ogv_df['group'].unique()

print(unique_groups)

['Crude & Products Tanker' 'Offshore Support Vessel' 'Chemical Tanker'
 'Container Ship' 'General Cargo' 'Passenger/Cruise' 'Bulk Carrier'
 'Auto Carrier' 'Reefer' 'RoRo' 'LPG Tanker']

In [17]:
#for checking

ogv_df = vessel_movements_PPT_df[vessel_movements_PPT_df['OGV'] == 'Non-OGV']

unique_groups = ogv_df['group'].unique()

print(unique_groups)

['Tug Boat' 'Other']

In [ ]:
#qns 4---------------------

In [23]:
import numpy as np

vessel_movements_PPT_df['date_of_build'] = pd.to_datetime(vessel_movements_PPT_df['date_of_build'])
conditions = [(vessel_movements_PPT_df['date_of_build'] >= pd.to_datetime('2000-01-01')),(vessel_movements_PPT_df['date_of_build'] >= pd.to_datetime('2011-01-01'))]
   

labels = ['Tier I', 'Tier II']

vessel_movements_PPT_df['Tier'] = pd.cut(vessel_movements_PPT_df['date_of_build'], 
                                          bins=[pd.to_datetime('2000-01-01'), pd.to_datetime('2011-01-01'), pd.to_datetime('2100-01-01')],
                                          labels=labels,
                                          include_lowest=True,
                                          right=False)
import numpy as np

vessel_movements_PPT_df.loc[vessel_movements_PPT_df['OGV'] == 'Non-OGV', 'Tier'] = np.nan

vessel_movements_PPT_df['Tier'].unique()

['Tier I', 'Tier II', NaN]
Categories (2, object): ['Tier I' < 'Tier II']

In [24]:
vessel_movements_PPT_df

,imo,mmsi,vessel_id,vessel_name,date_of_build,vessel_type,group,timestamp,date_only,lon,...,maneuvering_zone,p,vref,sfc_me,sfc_ae,sfc_ab,ael,abl,OGV,Tier
0,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:42.000Z,2023-09-17,103.826065,...,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV,Tier I
1,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:44.000Z,2023-09-17,103.826065,...,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV,Tier I
2,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:43.000Z,2023-09-17,103.825690,...,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV,Tier I
3,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:45.000Z,2023-09-17,103.825690,...,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV,Tier I
4,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:10:42.000Z,2023-09-17,103.825580,...,Unknown,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,OGV,Tier I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822594,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:59:17.000Z,2023-08-21,103.761665,...,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,0.0,0.0,OGV,Tier II
2822595,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:02:17.000Z,2023-08-21,103.761665,...,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,4493.0,908.0,OGV,Tier II
2822596,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:58:47.000Z,2023-08-21,103.783330,...,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,0.0,0.0,OGV,Tier II
2822597,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:47.000Z,2023-08-21,103.783330,...,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,2503.0,436.0,OGV,Tier II
2822598,9450313,636091832,647462,Northern Priority,2009-10-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:40.000Z,2023-08-21,103.766670,...,PPT Maneouvering Zone,36560.0,22.5,172.91,195.0,300.0,0.0,0.0,OGV,Tier I

In [25]:
#for checking (non-ogv will be nan for tier column)

unique_dates1 = vessel_movements_PPT_df[vessel_movements_PPT_df['OGV']== "Non-OGV"]["Tier"].unique()

unique_dates1

[NaN]
Categories (2, object): ['Tier I' < 'Tier II']

In [26]:
#for checking (both ogv/non-ogv with date before 2000 & non-ogv after 2000 will be nan )

unique_rows = vessel_movements_PPT_df[vessel_movements_PPT_df['Tier'].isnull()]

unique_dates = unique_rows[['date_of_build', 'OGV']].drop_duplicates()


unique_dates = unique_dates.sort_values(by='date_of_build')
unique_dates

        date_of_build      OGV
178925     1970-01-01      OGV
3777       1971-01-01  Non-OGV
705640     1973-01-01  Non-OGV
172101     1973-06-01      OGV
1207302    1973-12-01      OGV
...               ...      ...
44358      2023-04-01  Non-OGV
27003      2023-05-01  Non-OGV
602390     2023-06-01  Non-OGV
22314      2023-07-01  Non-OGV
1074232    2023-08-01  Non-OGV

[305 rows x 2 columns]